"""empty message

Revision ID: 0544b6fede50
Revises: c5c71dcd1e7f
Create Date: 2022-04-08 14:44:51.166361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0544b6fede50'
down_revision = 'c5c71dcd1e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
