"""empty message

Revision ID: 0c015482d168
Revises: 0544b6fede50
Create Date: 2022-04-08 14:48:27.939538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c015482d168'
down_revision = '0544b6fede50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
