"""empty message

Revision ID: 0f7749cc3844
Revises: b86f3c333b7c
Create Date: 2022-04-07 23:04:17.667877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7749cc3844'
down_revision = 'b86f3c333b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
