"""empty message

Revision ID: 455c08c792ea
Revises: 0c015482d168
Create Date: 2022-04-08 14:50:00.086731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455c08c792ea'
down_revision = '0c015482d168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
