"""empty message

Revision ID: a046e36d1e33
Revises: 0f7749cc3844
Create Date: 2022-04-08 12:57:02.048591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a046e36d1e33'
down_revision = '0f7749cc3844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
