"""empty message

Revision ID: b77a4c2de87a
Revises: d8a025747e92
Create Date: 2022-04-08 14:58:01.922135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77a4c2de87a'
down_revision = 'd8a025747e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
