"""empty message

Revision ID: c5c71dcd1e7f
Revises: e7d707183401
Create Date: 2022-04-08 14:42:37.729610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c71dcd1e7f'
down_revision = 'e7d707183401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
