"""empty message

Revision ID: e7d707183401
Revises: a046e36d1e33
Create Date: 2022-04-08 14:40:23.572861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d707183401'
down_revision = 'a046e36d1e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
